import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Suspense } from "react";
import Loading from "./loading";
import { Main } from "@/components/AnimationScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const Navbar = () => (
//   <nav className="flex items-center justify-between p-10">
//     <AuthButtons />
//   </nav>
// );

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className="bg-white text-gray-800">
            {/* <Navbar /> */}
            <Suspense fallback={<Loading />}>
              <Main>{children}</Main>
            </Suspense>
          </div>
        </body>
      </Providers>
    </html>
  );
}
